version:  "3.8"

services: 
   frontendimg:  
     build: /root/studentapp3tier_docker
     container_name : frontend
     ports :
       - "80:80"
     network_mode: 
      bridge
   backendimg:
     build: /root/studentapp3tier_docker
     container_name: backend
     depends_on: 
          - "frontendimg"
     ports: 
       - "8080:8080"
     network_mode: 
      bridge
